# CONFIGURACIÓN DE BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# CONFIGURACIÓN DE FLYWAY
spring.flyway.enabled=true

# MONITOREO Y ACTUATOR (ENDPOINTS)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never

# CONFIGURACIÓN DEL SERVIDOR
server.port=8080